# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 04:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrate',
            options={'verbose_name': '\u0410\u043a\u043a\u0430\u0443\u043d\u0442', 'verbose_name_plural': '\u0410\u043a\u043a\u0430\u0443\u043d\u0442\u044b'},
        ),
    ]
