# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 04:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coming', models.TimeField(blank=True, null=True, verbose_name='\u041f\u0440\u0438\u0448\u0435\u043b \u0432')),
                ('leaving', models.TimeField(blank=True, null=True, verbose_name='\u0423\u0448\u0435\u043b \u0432')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='\u0414\u0430\u0442\u0430')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_time', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u0420\u0430\u0431\u043e\u0447\u0435\u0435 \u0432\u0440\u0435\u043c\u044f',
                'verbose_name_plural': '\u0420\u0430\u0431\u043e\u0447\u0435\u0435 \u0432\u0440\u0435\u043c\u044f',
            },
        ),
    ]
