# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20170508_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingaccess',
            name='coming',
            field=models.TimeField(auto_now_add=True, verbose_name='\u041f\u0440\u0438\u0448\u0435\u043b \u0432'),
        ),
        migrations.AlterField(
            model_name='accountingaccess',
            name='leaving',
            field=models.TimeField(blank=True, null=True, verbose_name='\u0423\u0448\u0435\u043b \u0432'),
        ),
    ]
