# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20170509_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountingaccess',
            options={'verbose_name': '\u0420\u0430\u0431\u043e\u0447\u0435\u0435 \u0432\u0440\u0435\u043c\u044f', 'verbose_name_plural': '\u0420\u0430\u0431\u043e\u0447\u0435\u0435 \u0432\u0440\u0435\u043c\u044f'},
        ),
    ]
