# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 14:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20170509_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_time', to=settings.AUTH_USER_MODEL),
        ),
    ]
