# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 04:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043e\u0442\u0434\u0435\u043b\u0430')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='\u0421\u043b\u0430\u0433')),
                ('abbreviation', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u0410\u0431\u0431\u0440\u0435\u0432\u0438\u0430\u0442\u0443\u0440\u0430')),
            ],
            options={
                'verbose_name': '\u041e\u0442\u0434\u0435\u043b',
                'verbose_name_plural': '\u041e\u0442\u0434\u0435\u043b\u044b',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='\u0414\u043e\u043b\u0436\u043d\u043e\u0441\u0442\u044c')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='\u0421\u043b\u0430\u0433')),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='infrastructure.Departament', verbose_name='\u041e\u0442\u0434\u0435\u043b')),
            ],
            options={
                'verbose_name': '"\u0414\u043e\u043b\u0436\u043d\u043e\u0441\u0442\u044c"',
                'verbose_name_plural': '\u0414\u043e\u043b\u0436\u043d\u043e\u0441\u0442\u0438',
            },
        ),
    ]
