# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departament',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='\u0410\u0431\u0431\u0440\u0435\u0432\u0438\u0430\u0442\u0443\u0440\u0430'),
        ),
        migrations.AddField(
            model_name='departament',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='\u0421\u043b\u0430\u0433'),
        ),
        migrations.AddField(
            model_name='position',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='\u0421\u043b\u0430\u0433'),
        ),
    ]
