# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_auto_20170509_1620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departament',
            options={'verbose_name': '\u041e\u0442\u0434\u0435\u043b', 'verbose_name_plural': '\u041e\u0442\u0434\u0435\u043b\u044b'},
        ),
    ]
