# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0003_auto_20170509_2007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': '"\u0414\u043e\u043b\u0436\u043d\u043e\u0441\u0442\u044c"', 'verbose_name_plural': '\u0414\u043e\u043b\u0436\u043d\u043e\u0441\u0442\u0438'},
        ),
        migrations.AlterField(
            model_name='position',
            name='departament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='infrastructure.Departament', verbose_name='\u041e\u0442\u0434\u0435\u043b'),
        ),
    ]
